project: iot-blockchain
component: peer

replicaCount: 1
logging: DEBUG

devmode: true

peer:
  image:
    repository: hyperledger/fabric-peer
    pullPolicy: IfNotPresent
    tag: amd64-2.2.0
  service:
    type: ClusterIP
    port: 7051
    chaincodePort: 7052

ca:
  enabled: false
  image:
    repository: hyperledger/fabric-ca
    pullPolicy: IfNotPresent
    tag: amd64-1.4.7
  service:
    type: ClusterIP
    port: 7054

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure

resources: {}

affinity: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

artifacts:
  claim: artifacts.pvc

config:
  mspID: supplierMSP
  domain: supplier.iotchain.network
  peer: peer0
  tls: true

orderer:
  domain: iotchain.network
  hostname: orderer