project: iot-blockchain
component: peer

replicaCount: 1
logging: INFO

peer:
  image:
    repository: hyperledger/fabric-peer
    pullPolicy: IfNotPresent
    tag: amd64-2.2.0
  service:
    type: ClusterIP
    port: 7051
    chaincodePort: 7052

ca:
  image:
    repository: hyperledger/fabric-ca
    pullPolicy: IfNotPresent
    tag: amd64-1.4.7
  service:
    type: ClusterIP
    port: 7054

ingress:
  enabled: false
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    - host: orderer.com
      paths:
        - /
      middlewares: []
      services:
        - name: orderer
          port: 7050
          scheme: http

resources: {}

affinity: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

config:
  mspID: delivererMSP
  domain: deliverer.com
  peerSubdomain: peer0
  channelProfile: SupplyChannel
  channelID: supply-channel
  ordererProfile: OrdererGenesis
  crypto: |
  configtx: |