OrdererOrgs:
  - Name: Orderer
    Domain: iotchain.network
    Specs:
      - Hostname: orderer
        SANS:
          - orderer
          - localhost
PeerOrgs:
  - Name: Supplier
    Domain: supplier.iotchain.network
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        SANS:
          - peer0-supplier
          - localhost
    Users:
      Count: 1
  - Name: Deliverer
    Domain: deliverer.iotchain.network
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        SANS:
          - peer0-deliverer
          - localhost
    Users:
      Count: 1
