OrdererOrgs:
  - Name: Orderer
    Domain: orderer
    Specs:
      - Hostname: orderer
        CommonName: orderer
PeerOrgs:
  - Name: Supplier
    Domain: supplier
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        CommonName: peer0-supplier
    Users:
      Count: 1
  - Name: Deliverer
    Domain: deliverer
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        CommonName: peer0-deliverer
    Users:
      Count: 1
