network:
  orderer:
    name: Orderer
    type: etcdraft
    mspID: orderer
    hostname: orderer
    port: 7050
    profile: OrdererGenesis
    channelID: system-channel
  peerOrgs:
    - name: Chipa-INU
      mspID: chipa-inu
      hostname: chipa-inu.org
      peers:
        - subdomain: peer0
          service: peer0-chipa-inu
          port: 7051
      channelProfile: SupplyChannel
      channelID: supply-channel
    - name: Blueberry-GO
      mspID: blueberry-go
      hostname: blueberry-go.org
      peers:
        - subdomain: peer0
          service: peer0-blueberry-go
          port: 7051
      channelProfile: SupplyChannel
      channelID: supply-channel
    - name: MoonLAN
      mspID: moon-lan
      hostname: moon-lan.org
      peers:
        - subdomain: peer0
          service: peer0-moon-lan
          port: 7051
      channelProfile: SupplyChannel
      channelID: supply-channel
    - name: Blockchampion
      mspID: blockchampion
      hostname: blockchampion.org
      peers:
        - subdomain: peer0
          service: peer0-blockchampion
          port: 7051
      channelProfile: SupplyChannel
      channelID: supply-channel
    - name: SiGaN-Labs
      mspID: sigan-labs
      hostname: sigan-labs.org
      peers:
        - subdomain: peer0
          service: peer0-sigan-labs
          port: 7051
      channelProfile: SupplyChannel
      channelID: supply-channel
  channels:
    - name: SupplyChannel
      profile: SupplyChannel
      channelID: supply-channel
      consortium: SupplyConsortium
      organizations:
        - name: Chipa-INU
        - name: Blueberry-GO
        - name: MoonLAN
