apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ca
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ca.service.type }}
  ports:
    - name: ca
      port: {{ .Values.ca.service.port }}
      targetPort: {{ .Values.ca.service.port }}
  selector:
  {{- include "chart.selectorLabels" . | nindent 4 }}
