{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  entryPoints:
  {{- toYaml .Values.ingress.entrypoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.config.peer }}.{{ .Values.config.domain }}`)
      kind: Rule
      services:
        - name:  {{ .Values.config.peer}}-{{ .Release.Name }}
          port: {{ .Values.peer.service.port }}
          scheme: https
          {{- if .Values.config.tls }}
          serversTransport: {{ .Release.Name }}-transport
          {{- end }}
      middlewares:
    {{- if .Values.ca.enabled }}
    - match: Host(`ca.{{ .Values.config.domain }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-ca
          port: {{ .Values.ca.service.port }}
          scheme: https
      middlewares:
    {{- end -}}
  {{- if .Values.config.tls }}
  tls:
    secretName: {{ .Values.config.peer }}.{{ .Values.config.domain }}-tls
  {{- end }}
---
{{- if .Values.config.tls }}
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: {{ .Release.Name }}-transport
spec:
  serverName:  {{ .Values.config.peer}}-{{ .Release.Name }}
  rootCAsSecrets:
    - {{ .Values.config.peer }}.{{ .Values.config.domain }}-ca
  certificatesSecrets:
    - {{ .Values.config.peer }}.{{ .Values.config.domain }}-tls
---
{{- end }}
{{- end }}

