{{- if .Values.couchdb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb.{{ .Values.config.peer }}.{{ .Release.Name }}
  labels:
    app: couchdb.{{ .Values.config.peer }}.{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: couchdb.{{ .Values.config.peer }}.{{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: couchdb.{{ .Values.config.peer }}.{{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      containers:
      - name: couchdb
        image: "{{ .Values.couchdb.image.repository }}:{{ .Values.couchdb.image.tag }}"
        env:
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: couchdb-auth
                key: user
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: couchdb-auth
                key: password
{{- end -}}