project: iot-blockchain

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  routes:
    - host: proxy.chainmetric.network
      paths:
        - /
      middlewares:
        # - name: traefik-auth
      services:
        - name: api@internal
          kind: TraefikService
          port: 8080
          scheme: http
  tls:
    enabled: true
    certResolver: le
