project: iot-blockchain
component: orderer

replicaCount: 1
logging: DEBUG

image:
  repository: hyperledger/fabric-orderer
  pullPolicy: IfNotPresent
  tag: amd64-2.2.0

service:
  type: ClusterIP
  port: 7050

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: false
    certResolver: le
  routes:
    - host: orderer.iotchain.network
      paths:
        - /
      middlewares: []
      services:
        - name: orderer
          port: 7050
          scheme: http

resources: {}

affinity: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

artifacts:
  claim: artifacts.pvc

config:
  mspID: ordererMSP
  domain: orderer
  profile: OrdererGenesis
  tls: true