project: iot-blockchain
component: orderer

replicaCount: 1
logging: DEBUG

image:
  repository: hyperledger/fabric-orderer
  pullPolicy: IfNotPresent
  tag: amd64-2.2.0

service:
  type: ClusterIP
  port: 7050

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure

resources: {}

affinity: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

artifacts:
  claim: artifacts.pvc

config:
  mspID: ordererMSP
  domain: iotchain.network
  hostname: orderer.iotchain.network
  profile: OrdererGenesis
  tls: true

storageClass: local-path