project: iot-blockchain
component: orderer

replicaCount: 1
logging: INFO

image:
  repository: hyperledger/fabric-orderer
  pullPolicy: IfNotPresent
  tag: amd64-2.2.0

service:
  type: ClusterIP
  port: 7050

ingress:
  enabled: false
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    - host: orderer.com
      paths:
        - /
      middlewares: []
      services:
        - name: orderer
          port: 7050
          scheme: http

resources: {}

affinity: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

config:
  mspID: ordererMSP
  domain: orderer.com
  peerSubdomain: orderer
  ordererProfile: OrdererGenesis
  crypto: |
  configtx: |