image:
  name: traefik
  tag: "v2.4"
  pullPolicy: IfNotPresent

deployment:
  enabled: true
  kind: Deployment
  replicas: 1
  additionalContainers: []
  additionalVolumes: []
  initContainers: []

# Activate Pilot integration
pilot:
  enabled: false
  token: ""
  # Toggle Pilot Dashboard
  # dashboard: false

ingressRoute:
  dashboard:
    enabled: false

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

providers:
  kubernetesCRD:
    enabled: true
    namespaces: []
  kubernetesIngress:
    enabled: false

logs:
  general:
    level: DEBUG

additionalArguments:
  - --certificatesResolvers.le.acme.email=timothy@iotchain.network
  - --certificatesresolvers.le.acme.storage=/data/acme.json
  - --certificatesResolvers.le.acme.httpchallenge.entrypoint=web
#  - --certificatesResolvers.le.acme.dnschallenge.provider=cloudflare
#  - --certificatesResolvers.le.acme.dnsChallenge.resolvers="1.1.1.1:53"

env:
 - name: CF_DNS_API_TOKEN
   valueFrom:
     secretKeyRef:
       name: cf-dns-api-token
       key: token

ports:
  traefik:
    port: 8080
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
    # redirectTo: websecure
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
      certResolver: le
      domains:
       - main: chainmetric.network
         sans:
           - "*.chainmetric.network"

service:
  enabled: true
  type: LoadBalancer

autoscaling:
  enabled: false

persistence:
  enabled: false
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: local-path
  path: /data

rbac:
  enabled: true
