apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: {{ .Values.service.port }}
            - name: websecure
              containerPort: {{ .Values.service.securePort }}
            - name: admin
              containerPort: {{ .Values.service.adminPort }}
          args:
            - --api
            - --api.insecure={{ .Values.api.insecure }}
            - --api.dashboard={{ .Values.api.dashboard }}
            - --ping=true
            - --log.level={{ .Values.log.level }}
            - --providers.kubernetescrd={{ .Values.providers.kubernetescrd.enabled }}
            - --providers.kubernetesingress={{ .Values.providers.kubernetescrd.enabled }}
            - '--entryPoints.web.address=:{{ .Values.service.port}}'
            - '--entryPoints.websecure.address=:{{ .Values.service.securePort}}'
            - '--entryPoints.traefik.address=:{{ .Values.service.adminPort}}'
            {{- if .Values.acme.enabled }}
            - --certificatesResolvers.le.acme.email={{ .Values.acme.email}}
            - --certificatesResolvers.le.acme.storage={{ .Values.acme.storage}}
            - --certificatesResolvers.le.acme.dnschallenge={{ .Values.acme.dnsChallenge.enabled}}
            - --certificatesResolvers.le.acme.dnschallenge.provider={{ .Values.acme.dnsChallenge.provider}}
            {{- end }}
          {{- with .Values.serverTransport }}
            {{- with .rootCAs }}
            - --serversTransport.rootCAs={{.}}
            {{- end }}
            {{- with .insecureSkipVerify }}
            - --serversTransport.insecureSkipVerify={{.}}
            {{- end }}
          {{- end }}
          volumeMounts:
          {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
          {{- range .Values.secrets.mounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
          env:
            - name:  {{ .Values.acme.dnsChallenge.envName}}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.acme.dnsChallenge.tokenSecret }}
                  key: token
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.adminPort }}
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.adminPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- range .Values.volumes }}
        - name: {{ .name }}
        {{- with .host }}
          hostPath:
            path: {{ .pathBase }}{{ .path }}
            type: {{ .type }}
        {{- end }}
        {{- with .persistent }}
          persistentVolumeClaim:
            claimName: {{ .claim }}
        {{- end }}
      {{- end }}
      {{- range .Values.secrets.mounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
      {{- end }}