{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}{{- if .Values.ingress.tls.enabled }}.secure{{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entrypoints | nindent 4 }}
  routes:
    {{- range .Values.ingress.routes }}
    - match: Host(`{{ .host }}`) && PathPrefix(`{{ .paths | join "`) || PathPrefix(`" }}`)
      kind: Rule
      services:
        {{- range .services }}
        - name: {{ .name }}
          port: {{ .port }}
          kind: {{ .kind }}
          scheme: {{ .scheme }}
        {{- end }}
      {{- with .middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    certResolver: {{ .Values.ingress.tls.certResolver }}
  {{- end }}
---
  {{- if .Values.ingress.tls.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    {{- range .Values.ingress.routes }}
    - match: Host(`{{ .host }}`) && PathPrefix(`{{ .paths | join "`) || PathPrefix(`" }}`)
      kind: Rule
      services:
        {{- range .services }}
        - name: {{ .name }}
          port: {{ .port }}
          kind: {{ .kind }}
          scheme: {{ .scheme }}
      {{- end }}
      middlewares:
        - name: https-redirect
        {{- with .middlewares }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- end }}
---
  {{- end }}
{{- end }}