apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.chaincode }}.chaincodes.{{ .Values.peer }}"
  labels:
    app: "{{ .Values.chaincode }}.chaincodes.{{ .Values.peer }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.chaincode }}.chaincodes.{{ .Values.peer }}"
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: "{{ .Values.chaincode }}.chaincodes.{{ .Values.peer }}"
    {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: chaincode
          image: "{{.Values.image.repository }}:{{.Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CHAINCODE_CCID
              value: {{ .Values.ccid }}
            - name: CHAINCODE_ADDRESS
              value: "0.0.0.0:{{ .Values.service.port }}"
            - name: CHAINCODE_NAME
              value: "{{ .Values.peer }}-chaincode-{{ .Values.chaincode }}"
      restartPolicy: Always