{{- if .Values.storage.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}.pvc
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end -}}