apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.peer }}-chaincode-{{ .Values.chaincode }}"
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: peer
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
  {{- include "chart.selectorLabels" . | nindent 4 }}