apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}.crypto-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  crypto-config.yaml: |
    {{- $domain := .Values.domain }}
    {{ with .Values.config.orderer }}
    OrdererOrgs:
      - Name: {{ .name }}
        Domain: {{ $domain }}
        Specs:
          - Hostname: {{ .hostname }}
            SANS:
              - {{ .hostname }}
              - localhost
    {{ end }}
    PeerOrgs:
    {{- range .Values.config.organizations }}
      - Name: {{ .name }}
        Domain: {{ .hostname }}.{{ $domain }}
        EnableNodeOUs: true
        Specs:
        {{- range .peers }}
          - Hostname: {{ .hostname }}
            SANS:
              - {{ .service }}-org
              - localhost
        {{- end }}
        Users:
          Count: 1
    {{ end }}
